[package]
name = "bitwarden-send"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
hkdf = "0.12.4"
libaes = "0.7.0"
sha2 = "0.10.8"
wasm-bindgen = "0.2.100"
